#!/bin/sh
uci -q batch <<-EOF >/dev/null
delete ucitrack.@sysmonitor[-1]
add ucitrack sysmonitor
set ucitrack.@sysmonitor[-1].init=sysmonitor
commit ucitrack
EOF

sed -i '/exit 0/i\/usr\/share\/sysmonitor\/sysapp.sh firstrun' /etc/rc.local

#echo "[ \$INTERFACE = wan ] && /usr/share/sysmonitor/sysapp.sh re_sysmonitor" >/etc/hotplug.d/iface/90-sysmonitor
chmod 0600 /etc/dropbear/authorized_keys
chmod 0755 /etc/init.d/sysmonitor /usr/share/sysmonitor/*.sh

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache

exit 0
